// SPDX-License-Identifier: MIT OR Apache-2.0

//! Golden-vector conformance tests for packed dequantization.
//!
//! Expected outputs are generated by `tests/fixtures/golden/generate_golden.py`,
//! a bit-exact port of the llama.cpp scalar decoders
//! (`dequantize_row_q8_0` / `q5_K` / `q6_K` in `ggml/src/ggml-quants.c`,
//! tag b4800). For the three wire dtypes these are external-reference
//! conformance vectors covering PRNG blocks plus f16 zero, denormal, and
//! max scale fields. `iq3_m` vectors only lock in current behavior for
//! the internal (non-wire) 111-byte layout.
//!
//! Bit-exact equality is asserted (f32 bits), not approximate tolerance.

use engram_parser::{dequantize_iq3_m, dequantize_q5_k, dequantize_q6_k, dequantize_q8_0};

fn expected_f32(bytes: &[u8]) -> Vec<f32> {
    bytes
        .as_chunks::<4>()
        .0
        .iter()
        .map(|&c| f32::from_le_bytes(c))
        .collect()
}

fn check(name: &str, expected: &[u8], got: Vec<f32>) {
    let want = expected_f32(expected);
    assert_eq!(
        got.len(),
        want.len(),
        "{name}: element count {} != {}",
        got.len(),
        want.len()
    );
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        assert_eq!(
            g.to_bits(),
            w.to_bits(),
            "{name}: mismatch at index {i}: got {g:?}, want {w:?}"
        );
    }
}

#[test]
fn golden_q8_0() {
    let packed = include_bytes!("fixtures/golden/q8_0.packed.bin");
    let expected = include_bytes!("fixtures/golden/q8_0.expected.bin");
    check("q8_0", expected, dequantize_q8_0(packed, &[128]).unwrap());
}

#[test]
fn golden_q5_k() {
    let packed = include_bytes!("fixtures/golden/q5_k.packed.bin");
    let expected = include_bytes!("fixtures/golden/q5_k.expected.bin");
    check("q5_k", expected, dequantize_q5_k(packed, &[1024]).unwrap());
}

#[test]
fn golden_q6_k() {
    let packed = include_bytes!("fixtures/golden/q6_k.packed.bin");
    let expected = include_bytes!("fixtures/golden/q6_k.expected.bin");
    check("q6_k", expected, dequantize_q6_k(packed, &[1024]).unwrap());
}

#[test]
fn golden_iq3_m_regression() {
    let packed = include_bytes!("fixtures/golden/iq3_m.packed.bin");
    let expected = include_bytes!("fixtures/golden/iq3_m.expected.bin");
    check(
        "iq3_m",
        expected,
        dequantize_iq3_m(packed, &[1024]).unwrap(),
    );
}
